### ISSUE TITLE
Missing function?

### ISSUE THREAD

**Issue by Anetrom** [cccraig/MugShot#15]
After adding the Mugshot plugin, I get an error when reloading the piwigo page:

Fatal error: Call to undefined function array_column() in /var/www/html/piwigo/plugins/MugShot/main.inc.php on line 92

After inspecting the code, It looks like the "array_column" function indeed is missing from the file.

**Comment by amenk** [comment]
[array_column is a standard PHP function since 5.5](https://www.php.net/manual/de/function.array-column.php) -- on which PHP version are you running piwigo?
