### ISSUE TITLE
update to support piwigo 11

### ISSUE THREAD

**Issue by cccraig** [cccraig/MugShot#16]
Updates to make the plugin compatible with piwigo 11.

**Comment by amenk** [comment]
What needs to be done? Maybe I can try to support a bit. I am looking for this kind of functionality and did not find anything comparable. I tried with the old Piwigo version, but it's not running on recent PHP versions :-(

**Comment by amenk** [comment]
It's actually kind of working already with the master branch on Piwigo 11. After adding a group and allowing it to tag faces, it works in the Gallery view.

**Comment by cccraig** [comment]
Hey, the branch should actually work with piwigo 11. I need to make sure I
have all my tweaks in and then submit it to the plugin gallery.

**Comment by cccraig** [comment]
Hey, the branch "should" work right now. The main thing that needs doing is
to get it into the gallery with the versioning so that piwigo "knows" it's
compatible.
