### ISSUE TITLE
array_intersect() error

### ISSUE THREAD

**Issue by jwynn6** [cccraig/MugShot#3]
getting a floating error at the top of the homepage.

Warning: array_intersect(): Argument #1 is not an array in /var/www/html/plugins/MugShot/main.inc.php on line 45

**Comment by SvenErik1968** [comment]
I get the same/similar error (Piwigo 2.9.5 / PHP 7.2.13):

    Warning: array_intersect(): Argument #1 is not an array in /.../public_html/OldSiam/plugins/MugShot/main.inc.php on line 45

    Warning: count(): Parameter must be an array or an object that implements Countable in /.../public_html/OldSiam/plugins/MugShot/main.inc.php on line 48

**Comment by RaEyE** [comment]
Same here. Plugin-Version 1.2.1

Error-Message:
`Warning: count(): Parameter must be an array or an object that implements Countable in /config/www/gallery/plugins/MugShot/main.inc.php on line 163`


Server-Environment:
    Piwigo 2.9.5
    Operatingsystem: Linux
    PHP: 7.2.17 (Info anzeigen) [2019-05-05 18:10:02]
    MySQL: 5.7.26 [2019-05-05 18:10:02]
    GraphicsLibrary: ImageMagick 7.0.8-38

**Comment by amenk** [comment]
I believe this was fixed in 2.0.2 ?

**Comment by cccraig** [comment]
Should be fixed in the latest version.
